# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-30 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=30)),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
