book_list = ['java',
             'python',
             'vba',
             'sql',
             'linux',
             'data structure',
             'algorithm',
             'flask',
             'microservice',
             'docker',
             'data science',
             'pyspark',
             'big data',
             'visualization',
             'data warehouse',
             'Computer Organization',
             'computer architecture',
             'computer network',
             'discrete',
             'cryptography',
             'information safety',
             'linear algebra',
             'software engineering',
             'operating system',
             'sqlalchemy',
             ]
KEYWORD = 'sqlalchemy'
